"""Helper to (re)generate 002_seed.sql with deterministic fake data.

Run from the backend directory:
    python db/init/_generate_seed.py

The output is committed to the repo so docker-compose can apply it on a
fresh MySQL volume without requiring Python inside the container.

The seed creates:
  - A local dev user.
  - The local dev user's email on the auth_allowlist.
  - One "Home -> Work" trip for the dev user.
  - A full week of commute_samples for that trip (both directions, 06:00-21:00
    in 15-minute intervals, Monday-Sunday).
"""

from __future__ import annotations

import math
from datetime import date, datetime, time, timedelta, timezone
from pathlib import Path

OUT_PATH = Path(__file__).parent / "002_seed.sql"

TZ_OFFSET = timezone(timedelta(hours=-8))

DEV_EMAIL = "dev@example.com"
DEV_GOOGLE_SUB = "dev-local-000"
DEV_NAME = "Local Dev"

TRIP_NAME = "Home to Work"
TRIP_ORIGIN = "4585 Thousand Oaks Dr, San Jose, CA 95136"
TRIP_DESTINATION = "650 California St, San Francisco, CA 94108"

MONDAY = date(2025, 11, 10)
WEEKDAYS = [MONDAY + timedelta(days=i) for i in range(7)]

START_HOUR = 6
END_HOUR = 21
INTERVAL = timedelta(minutes=15)


def slots(day: date):
    start = datetime.combine(day, time(START_HOUR, 0), tzinfo=TZ_OFFSET)
    end = datetime.combine(day, time(END_HOUR, 0), tzinfo=TZ_OFFSET)
    cur = start
    while cur < end:
        yield cur
        cur += INTERVAL


def minutes_for(direction: str, ts: datetime) -> float:
    """Deterministic synthetic commute minutes with a plausible rush-hour shape."""
    hour = ts.hour + ts.minute / 60.0
    weekday = ts.weekday()
    weekday_bump = {0: 0, 1: 2, 2: 3, 3: 4, 4: 6}.get(weekday, -10)

    if direction == "outbound":
        base, peak_hour, amp = 40.0, 8.25, 45.0
    else:
        base, peak_hour, amp = 45.0, 17.5, 50.0

    bell = math.exp(-((hour - peak_hour) ** 2) / (2 * 0.9**2))
    jitter = 2.5 * math.sin(ts.day * 0.7 + ts.hour * 0.3 + ts.minute * 0.05)
    return round(base + amp * bell + weekday_bump + jitter, 1)


def escape(v: str) -> str:
    return v.replace("'", "''")


def sql_value(v) -> str:
    if v is None:
        return "NULL"
    if isinstance(v, str):
        return f"'{escape(v)}'"
    if isinstance(v, (int, float)):
        return str(v)
    raise TypeError(type(v))


def main() -> None:
    lines: list[str] = [
        "-- Auto-generated by db/init/_generate_seed.py. Do not edit by hand.",
        "-- Deterministic seed data for local dev and CI.",
        "USE traffic_larsjohansen_com;",
        "",
        "-- Local dev user and allowlist entry.",
        f"INSERT IGNORE INTO auth_allowlist (email, added_by) VALUES ({sql_value(DEV_EMAIL)}, 'seed');",
        "INSERT IGNORE INTO users (google_sub, email, name) VALUES (",
        f"    {sql_value(DEV_GOOGLE_SUB)}, {sql_value(DEV_EMAIL)}, {sql_value(DEV_NAME)}",
        ");",
        "",
        "-- Dev user's Home -> Work trip.",
        "INSERT IGNORE INTO trips (user_id, name, origin_address, destination_address) VALUES (",
        f"    (SELECT id FROM users WHERE email = {sql_value(DEV_EMAIL)}),",
        f"    {sql_value(TRIP_NAME)}, {sql_value(TRIP_ORIGIN)}, {sql_value(TRIP_DESTINATION)}",
        ");",
        "",
        "-- One week of synthetic commute samples for that trip.",
        "SET @trip_id := (",
        f"    SELECT id FROM trips WHERE origin_address = {sql_value(TRIP_ORIGIN)}",
        f"      AND destination_address = {sql_value(TRIP_DESTINATION)} LIMIT 1",
        ");",
        "",
        "INSERT IGNORE INTO commute_samples",
        "    (trip_id, week_start_date, direction, date_local, weekday, hhmm,",
        "     local_departure_time, departure_time_rfc3339, distance_meters,",
        "     duration_seconds, `condition`, status_code, status_message)",
        "VALUES",
    ]

    week_start_iso = MONDAY.isoformat()
    rows: list[str] = []
    for day in WEEKDAYS:
        for direction in ("outbound", "return"):
            distance = 78000 if direction == "outbound" else 78500
            for ts in slots(day):
                minutes = minutes_for(direction, ts)
                duration_seconds = int(round(minutes * 60))
                local_display = ts.strftime("%Y-%m-%d %H:%M:%S %Z")
                hhmm = ts.strftime("%H:%M")
                weekday_num = ts.weekday()
                rows.append(
                    "    (@trip_id, "
                    + ", ".join(
                        [
                            sql_value(week_start_iso),
                            sql_value(direction),
                            sql_value(ts.date().isoformat()),
                            sql_value(weekday_num),
                            sql_value(hhmm),
                            sql_value(local_display),
                            sql_value(ts.isoformat()),
                            sql_value(distance),
                            sql_value(duration_seconds),
                            sql_value("TRAFFIC_CONDITION_NORMAL"),
                            sql_value("OK"),
                            sql_value(""),
                        ]
                    )
                    + ")"
                )

    lines.append(",\n".join(rows) + ";")
    lines.append("")

    OUT_PATH.write_text("\n".join(lines))
    print(f"Wrote {len(rows)} sample rows to {OUT_PATH}")


if __name__ == "__main__":
    main()
