"""Helper to (re)generate 002_seed.sql with deterministic fake commute data.

Run from the backend directory:
    python db/init/_generate_seed.py

The output is committed to the repo so docker-compose can apply it on a
fresh MySQL volume without requiring Python inside the container.
"""

from __future__ import annotations

import math
from datetime import date, datetime, time, timedelta, timezone
from pathlib import Path

OUT_PATH = Path(__file__).parent / "002_seed.sql"
TZ_OFFSET = timezone(timedelta(hours=-8))  # Fixed PST for reproducibility.

# Anchor on a recent Monday so the data looks plausibly current. Keep this
# fixed so the file is stable across regenerations (run this by hand when
# you want fresher dates).
MONDAY = date(2025, 11, 10)
WEEKDAYS = [MONDAY + timedelta(days=i) for i in range(5)]

INTERVAL = timedelta(minutes=15)
H2W_WINDOW = (time(5, 0), time(13, 0))
W2H_WINDOW = (time(12, 0), time(20, 0))


def slots(day: date, window: tuple[time, time]):
    start = datetime.combine(day, window[0], tzinfo=TZ_OFFSET)
    end = datetime.combine(day, window[1], tzinfo=TZ_OFFSET)
    cur = start
    while cur < end:
        yield cur
        cur += INTERVAL


def minutes_for(direction: str, ts: datetime) -> float:
    """Deterministic synthetic commute minutes with a plausible rush-hour shape."""
    hour = ts.hour + ts.minute / 60.0
    weekday_bump = {0: 0, 1: 2, 2: 3, 3: 4, 4: 6}.get(ts.weekday(), 0)

    if direction == "H2W":
        base = 40.0
        peak_hour = 8.25
        peak_amplitude = 45.0
    else:
        base = 45.0
        peak_hour = 17.5
        peak_amplitude = 50.0

    bell = math.exp(-((hour - peak_hour) ** 2) / (2 * 0.9**2))
    jitter = 2.5 * math.sin(ts.day * 0.7 + ts.hour * 0.3 + ts.minute * 0.05)
    return round(base + peak_amplitude * bell + weekday_bump + jitter, 1)


def escape(v: str) -> str:
    return v.replace("'", "''")


def sql_value(v) -> str:
    if v is None:
        return "NULL"
    if isinstance(v, str):
        return f"'{escape(v)}'"
    if isinstance(v, (int, float)):
        return str(v)
    raise TypeError(type(v))


def main() -> None:
    lines: list[str] = [
        "-- Auto-generated by db/init/_generate_seed.py. Do not edit by hand.",
        "-- Deterministic fake commute data for local dev and CI.",
        "USE traffic_larsjohansen_com;",
        "",
        "INSERT IGNORE INTO commute_slots",
        "    (date_local, local_departure_time, departure_time_rfc3339, direction,",
        "     distance_meters, duration, `condition`, status_code, status_message)",
        "VALUES",
    ]

    rows: list[str] = []
    for day in WEEKDAYS:
        for direction, window in (("H2W", H2W_WINDOW), ("W2H", W2H_WINDOW)):
            distance = 78000 if direction == "H2W" else 78500
            for ts in slots(day, window):
                minutes = minutes_for(direction, ts)
                duration_str = f"{int(round(minutes * 60))}s"
                local_display = ts.strftime("%Y-%m-%d %H:%M:%S %Z") or ts.strftime(
                    "%Y-%m-%d %H:%M:%S PST"
                )
                rfc3339 = ts.isoformat()
                rows.append(
                    "    ("
                    + ", ".join(
                        [
                            sql_value(ts.date().isoformat()),
                            sql_value(local_display),
                            sql_value(rfc3339),
                            sql_value(direction),
                            sql_value(distance),
                            sql_value(duration_str),
                            sql_value("TRAFFIC_CONDITION_NORMAL"),
                            sql_value("OK"),
                            sql_value(""),
                        ]
                    )
                    + ")"
                )

    lines.append(",\n".join(rows) + ";")
    lines.append("")

    OUT_PATH.write_text("\n".join(lines))
    print(f"Wrote {len(rows)} rows to {OUT_PATH}")


if __name__ == "__main__":
    main()
