/**
 * Dynamic Expo config.
 *
 * Strict by design — every input is required, and any missing value
 * throws at config-load time so `expo start` / `eas build` fails
 * immediately with a precise message instead of producing a broken
 * binary.
 *
 * Required env (read at config-load, before the runtime bundle even
 * exists):
 *
 *   EXPO_PUBLIC_APP_ENV                       "local" | "prod"
 *   EXPO_PUBLIC_GOOGLE_OAUTH_IOS_CLIENT_ID    only when APP_ENV=prod
 *
 * The iOS URL scheme registered with the `@react-native-google-signin`
 * config plugin is **always** derived from the iOS client ID — it's
 * literally the client ID with the reverse-DNS prefix
 * `com.googleusercontent.apps.` swapped in for the
 * `.apps.googleusercontent.com` suffix, so deriving it removes a
 * separate, error-prone env var the developer would otherwise need
 * to keep in sync.
 *
 * Expo loads `apps/mobile/.env` automatically before reading this
 * file (since SDK 49), so plain `process.env.*` reads work both
 * locally and in cloud builds via EAS secrets.
 */
import type { ExpoConfig, ConfigContext } from "expo/config";
import { withXcodeProject, type ConfigPlugin } from "@expo/config-plugins";

const GOOGLE_CLIENT_SUFFIX = ".apps.googleusercontent.com";

/**
 * Disables Xcode 15+'s "user script sandbox" for the iOS project.
 *
 * React Native's `Bundle React Native code and images` script and
 * `expo-dev-launcher`'s `Strip Local Network Keys for Release` script
 * both write files (e.g. `ip.txt`) into the .app bundle. The default
 * Xcode 15+ user-script sandbox blocks any write that isn't pre-declared
 * in the script's outputs section, breaking the build with:
 *
 *   error: Sandbox: bash(NNNN) deny(1) file-write-create
 *     /…/Build/Products/Debug-iphoneos/time2leave.app/ip.txt
 *
 * Disabling user-script sandboxing for our project (`ENABLE_USER_SCRIPT_SANDBOXING=NO`)
 * is the standard fix until React Native ships a script with proper
 * input/output declarations. The flag has no runtime effect — it only
 * controls what build scripts are allowed to do at *build* time.
 *
 * Because `apps/mobile/ios/` is gitignored and regenerated by every
 * `expo prebuild`, we apply this as a config plugin so the setting
 * survives a clean prebuild instead of being a manual checkbox in
 * Xcode that has to be re-toggled after every prebuild.
 */
const withDisabledUserScriptSandboxing: ConfigPlugin = (config) =>
    withXcodeProject(config, (cfg) => {
        const project = cfg.modResults;
        const buildConfigs = project.pbxXCBuildConfigurationSection() as Record<
            string,
            { buildSettings?: Record<string, string> } | string
        >;
        for (const key of Object.keys(buildConfigs)) {
            const entry = buildConfigs[key];
            if (entry && typeof entry === "object" && entry.buildSettings) {
                entry.buildSettings.ENABLE_USER_SCRIPT_SANDBOXING = "NO";
            }
        }
        return cfg;
    });

function deriveIosUrlScheme(clientId: string): string {
    if (!clientId.endsWith(GOOGLE_CLIENT_SUFFIX)) {
        throw new Error(
            `EXPO_PUBLIC_GOOGLE_OAUTH_IOS_CLIENT_ID has an unexpected format: ${JSON.stringify(
                clientId,
            )}. ` +
                `Expected an iOS OAuth client ID ending in "${GOOGLE_CLIENT_SUFFIX}" — copy the iOS client ID exactly from Google Cloud Console > APIs & Services > Credentials.`,
        );
    }
    const prefix = clientId.slice(0, -GOOGLE_CLIENT_SUFFIX.length);
    return `com.googleusercontent.apps.${prefix}`;
}

export default ({ config }: ConfigContext): ExpoConfig => {
    const appEnv = process.env.EXPO_PUBLIC_APP_ENV?.trim();
    if (appEnv !== "local" && appEnv !== "prod") {
        throw new Error(
            `EXPO_PUBLIC_APP_ENV must be set to "local" or "prod" in apps/mobile/.env. ` +
                `Got: ${JSON.stringify(appEnv)}. See apps/mobile/.env.example for the canonical templates.`,
        );
    }

    // The typed `ExpoConfig["plugins"]` only allows strings + string tuples
    // (the on-disk JSON shape), but Expo's runtime accepts inline plugin
    // functions just fine. We cast our local plugin function to satisfy
    // the schema; behaviorally it's identical.
    const plugins: NonNullable<ExpoConfig["plugins"]> = [
        "expo-router",
        "expo-secure-store",
        // Adds the `com.apple.developer.applesignin = ["Default"]`
        // entitlement to the iOS app so AuthenticationServices can
        // present the native "Sign in with Apple" sheet. Available
        // in both `local` and `prod` mode — Apple Sign In doesn't
        // need a Cloud Console client ID; the backend just verifies
        // the JWT against Apple's public JWKs using our bundle ID
        // as the audience.
        //
        // External one-time setup the developer must still do at
        // developer.apple.com: add the "Sign in with Apple"
        // capability to the App ID for `com.time2leave.app`. Xcode
        // re-syncs the provisioning profile automatically on the
        // next build after that's enabled.
        "expo-apple-authentication",
        // Splash screen: we render the brand mark on a clean canvas
        // that matches each color scheme's app background. The image
        // itself is a transparent-canvas variant of the icon (see
        // `scripts/generate-icons.mjs`) so a comfortable margin
        // surrounds the tile at every device width. `imageWidth` keeps
        // the tile to ~52% of the screen — same proportional weight
        // as the wordmark in the web splash hero.
        [
            "expo-splash-screen",
            {
                image: "./assets/splash-icon.png",
                imageWidth: 220,
                resizeMode: "contain",
                backgroundColor: "#f8fafc",
                dark: {
                    image: "./assets/splash-icon.png",
                    backgroundColor: "#0b1020",
                },
            },
        ],
        withDisabledUserScriptSandboxing as unknown as string,
    ];

    if (appEnv === "prod") {
        // Prod builds always use native Google Sign-In, so the iOS
        // OAuth client ID + URL scheme must be present.
        const iosClientId = process.env.EXPO_PUBLIC_GOOGLE_OAUTH_IOS_CLIENT_ID?.trim();
        if (!iosClientId) {
            throw new Error(
                'EXPO_PUBLIC_GOOGLE_OAUTH_IOS_CLIENT_ID is required when EXPO_PUBLIC_APP_ENV="prod". ' +
                    "Create an iOS OAuth client for bundle ID com.time2leave.app in Google Cloud Console and put the client ID in apps/mobile/.env.",
            );
        }
        const iosUrlScheme = deriveIosUrlScheme(iosClientId);
        plugins.push([
            "@react-native-google-signin/google-signin",
            { iosUrlScheme },
        ]);
    }

    return {
        ...config,
        // Display name shown under the icon on every launcher / home
        // screen. We use the camel-cased "Time2Leave" form here (rather
        // than the lowercase `time2leave` we use as the slug / bundle ID
        // / scheme) so the storefront listing and the system app
        // launcher both render the brand the same way the web wordmark
        // does — capitalized at title-case sentence positions while the
        // signature italic "2" still reads as the accent glyph.
        name: "Time2Leave",
        slug: "time2leave",
        version: "1.0.0",
        orientation: "portrait",
        scheme: "time2leave",
        userInterfaceStyle: "automatic",
        icon: "./assets/icon.png",
        // The New Architecture is mandatory in Expo SDK 55, so the
        // legacy `newArchEnabled: true` flag is no longer needed (and
        // is no longer part of the typed `ExpoConfig` schema).
        //
        // EAS Update configuration. `updates.url` is the project's
        // dedicated update endpoint on Expo's CDN — the runtime
        // (added by `expo-updates`) HEADs it on cold start and
        // applies any newer JS bundle published with
        // `eas update --channel <name>`. The channel comes from
        // `eas.json`'s `production.channel` ("production"); pairing
        // a build channel with the `appVersion` runtime-version
        // policy means an OTA update only ships to installs whose
        // native version (`expo.version`, currently 1.0.0) matches —
        // bumping `version` therefore guarantees we never push a JS
        // bundle to a binary that doesn't have the matching native
        // modules. Re-run `eas update:configure` after rotating the
        // EAS project to regenerate the `url`.
        updates: {
            url: "https://u.expo.dev/115f5bad-adec-4e0b-8bc5-309bb3180b3b",
        },
        runtimeVersion: {
            policy: "appVersion",
        },
        ios: {
            supportsTablet: true,
            bundleIdentifier: "com.time2leave.app",
            infoPlist: {
                ITSAppUsesNonExemptEncryption: false,
            },
        },
        android: {
            // Edge-to-edge layout is the default on Android in Expo SDK
            // 55 with the New Architecture, so we don't need an explicit
            // `edgeToEdgeEnabled: true` here anymore.
            package: "com.time2leave.app",
            adaptiveIcon: {
                // Foreground PNG is full-bleed gradient + "2" — when
                // the launcher applies its mask (circle, squircle, or
                // teardrop) the gradient is what shows through. The
                // "2" is sized to stay inside Android's 66% safe-zone
                // circle so no launcher crops it.
                foregroundImage: "./assets/adaptive-icon.png",
                // Solid backdrop visible only at the very corners that
                // the launcher mask leaves exposed. We pick the brand
                // primary so it harmonises with the warm gradient
                // rather than cutting through it.
                backgroundColor: "#1e40af",
            },
        },
        web: {
            bundler: "metro",
            output: "static",
            favicon: "./assets/favicon.png",
        },
        plugins,
        experiments: {
            typedRoutes: true,
        },
        extra: {
            router: {
                origin: false,
            },
            // EAS project ID — populated by `eas init` and required
            // for every cloud build / submit so the EAS CLI can
            // associate the local checkout with its remote project
            // (`@larskrjo/time2leave`). Because we use a dynamic
            // `app.config.ts`, the CLI cannot write this value back
            // for us; it's committed by hand. Don't change it
            // without re-running `eas init` — builds will be
            // attributed to the wrong project otherwise.
            eas: {
                projectId: "115f5bad-adec-4e0b-8bc5-309bb3180b3b",
            },
        },
    };
};
